[package]
name = "se"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
chrono = "0.4.38"
eframe = "0.29.1"
egui_extras = { version = "0.29.1", features = ["all_loaders", "datepicker"] }
regex = "1.11.1"
rusqlite = "0.32.1"
strum = { version = "0.26.3", features = ["derive"] }
